version: '3.8'

services:

  # Web Server Service
  nginx:
    container_name: sts_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
    restart: always

  #Database Service
  db:
    container_name : sts_mysql
    image : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sts
      MYSQL_ROOT_PASSWORD: password
    restart: always

  # db:
  #   image: postgres
  #   container_name: postgres
  #   volumes:
  #     - ./postgresql/data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: main_db
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: password
  #   restart: always

  # Application Service
  app:
    container_name: sts_app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    restart: always

  #phpMyAdmin Service
  phpmyadmin:
    container_name: sts_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db
    restart: always
  # pgadmin:
  #   container_name: pgAdmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin6@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   restart: always
